#!/usr/bin/env python3
"""
Standalone test for _validate_chunking_coverage function.
Copies the function here to avoid import issues.
"""

from typing import List, Dict, Tuple
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def _validate_chunking_coverage(document_content: str, chunks: List[Dict]) -> Tuple[bool, str]:
    """
    Validate that LLM chunking adequately covered the input document.
    """
    if not chunks:
        return False, "No chunks generated by LLM"
    
    # Calculate total chunked content length
    total_chunked_length = sum(len(c.get('content', '')) for c in chunks)
    input_length = len(document_content)
    
    if input_length == 0:
        return False, "Empty document content"
    
    # Calculate coverage ratio
    coverage_ratio = total_chunked_length / input_length
    
    # === Minimum chunk count validation ===
    estimated_chunks_needed = max(1, input_length // 1000)
    min_expected_chunks = max(3, estimated_chunks_needed)
    
    chunk_count_warning = ""
    if len(chunks) < min_expected_chunks:
        chunk_count_warning = (
            f"Suspiciously few chunks: {len(chunks)} generated vs "
            f"~{min_expected_chunks} expected for {input_length}-char document. "
            f"Expected ~1 chunk per 1000 characters."
        )
        logger.warning(f"Chunk count validation WARNING: {chunk_count_warning}")
    
    # Log coverage for monitoring
    logger.info(
        f"Chunking coverage validation: "
        f"input={input_length} chars, "
        f"chunked={total_chunked_length} chars, "
        f"coverage={coverage_ratio:.1%}, "
        f"chunks={len(chunks)} (expected ~{min_expected_chunks})"
    )
    
    # Critical threshold: Less than 50% coverage is a hard failure
    if coverage_ratio < 0.50:
        error_msg = (
            f"Insufficient content coverage: {coverage_ratio:.1%} "
            f"({total_chunked_length}/{input_length} chars in {len(chunks)} chunks). "
            f"Expected >50%. LLM may have stopped prematurely or document is too large."
        )
        logger.error(f"Coverage validation FAILED: {error_msg}")
        return False, error_msg
    
    # Warning threshold: Less than 70% coverage OR insufficient chunk count
    warnings = []
    if coverage_ratio < 0.70:
        warnings.append(
            f"Low content coverage: {coverage_ratio:.1%} "
            f"({total_chunked_length}/{input_length} chars). "
            f"Expected >70%. Some content may be missing."
        )
    
    if chunk_count_warning:
        warnings.append(chunk_count_warning)
    
    if warnings:
        warning_msg = " | ".join(warnings)
        logger.warning(f"Chunking validation warnings: {warning_msg}")
        return True, warning_msg
    
    # Good coverage
    logger.info(f"Coverage validation PASSED: {coverage_ratio:.1%}")
    return True, ""


def test_full_coverage():
    """Test case: Good coverage (>70%)"""
    print("Test 1: Full coverage (>70%)")
    doc = "A" * 10000
    chunks = [{'content': "A" * 800, 'chunk_id': f'chunk_{i}'} for i in range(10)]
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Total chunked: {sum(len(c['content']) for c in chunks)} chars")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg if msg else '(none)'}")
    assert valid == True, f"Expected valid=True, got {valid}"
    assert msg == "", f"Expected no message, got: {msg}"
    print("  ✅ PASSED\n")

def test_low_coverage_failure():
    """Test case: Very low coverage (<50%) - should fail"""
    print("Test 2: Low coverage (<50%) - should FAIL")
    doc = "A" * 10000
    chunks = [{'content': "A" * 100, 'chunk_id': 'chunk_0'}]  # Only 1%
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Total chunked: {sum(len(c['content']) for c in chunks)} chars")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg[:100]}...")
    assert valid == False, f"Expected valid=False, got {valid}"
    assert "insufficient" in msg.lower() or "coverage" in msg.lower(), f"Expected coverage error in: {msg}"
    print("  ✅ PASSED\n")

def test_warning_coverage():
    """Test case: Medium coverage (50-70%) - should warn"""
    print("Test 3: Medium coverage (50-70%) - should WARN")
    doc = "A" * 10000
    chunks = [{'content': "A" * 600, 'chunk_id': f'chunk_{i}'} for i in range(10)]  # 60%
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Total chunked: {sum(len(c['content']) for c in chunks)} chars")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg[:100]}...")
    assert valid == True, f"Expected valid=True, got {valid}"
    assert "low" in msg.lower(), f"Expected warning in: {msg}"
    print("  ✅ PASSED\n")

def test_few_chunks_warning():
    """Test case: Large doc with few chunks - should warn"""
    print("Test 4: Large doc with few chunks - should WARN")
    doc = "A" * 50000  # Should need ~50 chunks
    chunks = [{'content': "A" * 1000, 'chunk_id': f'chunk_{i}'} for i in range(20)]  # 20 chunks, 40%
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Total chunked: {sum(len(c['content']) for c in chunks)} chars")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg[:100]}...")
    # Coverage is 40%, should fail
    assert valid == False, f"Expected valid=False (low coverage), got {valid}"
    print("  ✅ PASSED\n")

def test_real_scenario():
    """Test case: Simulate job_277abcdb4a83 scenario"""
    print("Test 5: Real scenario (job_277abcdb4a83)")
    doc = "A" * 155571  # Original document size
    chunks = [
        {'content': "A" * 122, 'chunk_id': 'chunk_0'},
        {'content': "A" * 569, 'chunk_id': 'chunk_1'}
    ]  # Only 691 chars total = 0.44%
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Total chunked: {sum(len(c['content']) for c in chunks)} chars")
    coverage = sum(len(c['content']) for c in chunks) / len(doc) * 100
    print(f"  Coverage: {coverage:.2f}%")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg[:150]}...")
    assert valid == False, f"Expected valid=False, got {valid}"
    assert "insufficient" in msg.lower() or "coverage" in msg.lower(), f"Expected coverage error"
    print("  ✅ PASSED - This would have caught job_277abcdb4a83 failure!\n")

def test_empty_chunks():
    """Test case: No chunks generated"""
    print("Test 6: Empty chunks - should FAIL")
    doc = "A" * 1000
    chunks = []
    
    valid, msg = _validate_chunking_coverage(doc, chunks)
    
    print(f"  Input: {len(doc)} chars, {len(chunks)} chunks")
    print(f"  Valid: {valid}")
    print(f"  Message: {msg}")
    assert valid == False, f"Expected valid=False, got {valid}"
    assert "no chunks" in msg.lower(), f"Expected 'no chunks' error"
    print("  ✅ PASSED\n")

if __name__ == "__main__":
    print("=" * 60)
    print("Chunking Quality Validation - Unit Tests")
    print("=" * 60 + "\n")
    
    try:
        test_full_coverage()
        test_low_coverage_failure()
        test_warning_coverage()
        test_few_chunks_warning()
        test_real_scenario()
        test_empty_chunks()
        
        print("=" * 60)
        print("✅ ALL TESTS PASSED!")
        print("=" * 60)
    except AssertionError as e:
        print(f"\n❌ TEST FAILED: {e}")
        import sys
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ UNEXPECTED ERROR: {e}")
        import traceback
        traceback.print_exc()
        import sys
        sys.exit(1)
